---
authors:
  - Sumit Jaiswal (@justjais)
dependencies:
  "cisco.asa": ">=3.0.0"
  "ansible.netcommon": ">=1.13.0"
license_file: LICENSE
name: firewall_mgmt
namespace: security
description: Ansible Collection to build, maintain and validate FW management and policy over firewall appliances.
readme: README.md
repository: https://github.com/redhat-cop/security.firewall_mgmt
issues: https://github.com/redhat-cop/security.firewall_mgmt/issues
tags: [security, firewall, firewall management, asa]
version: null
